theme: 2
showNotifications: true
fontFamily: TsangerJinKai01-27533
mixinType: 1
mixinCode: |
  module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
    const rules = content.rules;
    rules.unshift(
      ...[
        "DOMAIN-SUFFIX,qima-inc.com,ğŸš€ç›´æ¥è¿æ¥", // å…¬å¸å†…ç½‘
        "DOMAIN-SUFFIX,delivery.mp.microsoft.com,ğŸš€ç›´æ¥è¿æ¥", // åº”ç”¨å•†åº—æ™ºèƒ½åˆ†å‘
        "DOMAIN-SUFFIX,xvcf1.xboxlive.com,ğŸš€ç›´æ¥è¿æ¥", // xboxä¸‹è½½
        "DOMAIN-SUFFIX,jinkela.red,ğŸš€ç›´æ¥è¿æ¥", // æ¢¯å­
        "DOMAIN-SUFFIX,epicgames-download1.akamaized.net,ğŸš€ç›´æ¥è¿æ¥", // epic games
        "DOMAIN-SUFFIX,reddit.com,ğŸ”°å›½å¤–æµé‡",
        "DOMAIN-SUFFIX,redditstatic.com,ğŸ”°å›½å¤–æµé‡",
        "DOMAIN-SUFFIX,redditmedia.com,ğŸ”°å›½å¤–æµé‡",
      ]
    );
    return content;
  };
showNewVersionIcon: true
editor: 1
hideAfterStartup: true
randomControllerPort: true
mixinText: |
  mixin: # object
