theme: 2
showNotifications: true
fontFamily: TsangerJinKai01-27533
mixinType: 1
mixinCode: |
  module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
    const rules = content.rules;
    rules.unshift(
      ...[
        "DOMAIN-SUFFIX,qima-inc.com,ğŸš€ ç»•è¿‡ä»£ç†", // å…¬å¸å†…ç½‘
        "DOMAIN-SUFFIX,delivery.mp.microsoft.com,ğŸš€ ç»•è¿‡ä»£ç†", // åº”ç”¨å•†åº—æ™ºèƒ½åˆ†å‘
        "DOMAIN-SUFFIX,xvcf1.xboxlive.com,ğŸš€ ç»•è¿‡ä»£ç†", // xboxä¸‹è½½
        "DOMAIN-SUFFIX,jinkela.red,ğŸš€ ç»•è¿‡ä»£ç†", // æ¢¯å­
        "DOMAIN-SUFFIX,epicgames-download1.akamaized.net,ğŸš€ ç»•è¿‡ä»£ç†", // epic games
        "DOMAIN-SUFFIX,json.schemastore.org,â˜ï¸ å…¶ä»–æµé‡",
        "DOMAIN-SUFFIX,reddit.com,â˜ï¸ å…¶ä»–æµé‡",
        "DOMAIN-SUFFIX,redditstatic.com,â˜ï¸ å…¶ä»–æµé‡",
        "DOMAIN-SUFFIX,redditmedia.com,â˜ï¸ å…¶ä»–æµé‡",
      ]
    );
    return content;
  };
showNewVersionIcon: true
editor: 1
hideAfterStartup: true
randomControllerPort: true
mixinText: |
  mixin: # object
runTimeFormat: "hh : mm : ss"
