theme: 2
showNotifications: true
fontFamily: TsangerJinKai01-27533
mixinType: 1
mixinCode: |-
  module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
    const rules = [
      'DOMAIN-SUFFIX,qima-inc.com,ğŸ¯ å…¨çƒç›´è¿',
      'DOMAIN-SUFFIX,delivery.mp.microsoft.com,ğŸ¯ å…¨çƒç›´è¿',
      'DOMAIN-SUFFIX,jinkela.red,ğŸ¯ å…¨çƒç›´è¿',
      ...content.rules
    ];
    return { ...content, rules };
  }
showNewVersionIcon: true
