theme: 2
showNotifications: true
fontFamily: TsangerJinKai01-27533
mixinType: 1
mixinCode: |-
  module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
    const rules = [
      ...content.rules,
      'DOMAIN-SUFFIX,qima-inc.com,ğŸ¯ å…¨çƒç›´è¿'
    ];
    return { ...content, rules };
  }
