theme: 2
showNotifications: true
fontFamily: TsangerJinKai01-27533
mixinType: 1
mixinCode: >
  module.exports.parse = ({ content, name, url }, { yaml, axios, notify
  }) => {
    const rules = content.rules;
    rules.unshift(
      ...[
        "DOMAIN-SUFFIX,cdn.winget.microsoft.com,ğŸƒ Proxies", // winget
        "DOMAIN-SUFFIX,self.events.data.microsoft.com,ğŸƒ Proxies", // winget
        "DOMAIN-SUFFIX,json.schemastore.org,ğŸƒ Proxies",
        "DOMAIN-SUFFIX,reddit.com,ğŸƒ Proxies",
        "DOMAIN-SUFFIX,redditstatic.com,ğŸƒ Proxies",
        "DOMAIN-SUFFIX,redditmedia.com,ğŸƒ Proxies",
        "DOMAIN-SUFFIX,steampowered.com,ğŸƒ Proxies",
        "DOMAIN-SUFFIX,steam-chat.com,ğŸƒ Proxies",
        "DOMAIN-SUFFIX,api.epicgames.com,ğŸƒ Proxies",
        "DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,ğŸƒ Proxies",
        "DOMAIN-SUFFIX,delivery.mp.microsoft.com,ğŸ‚ Domestic", // åº”ç”¨å•†åº—æ™ºèƒ½åˆ†å‘
        "DOMAIN-SUFFIX,xvcf1.xboxlive.com,ğŸ‚ Domestic", // xboxä¸‹è½½
        "DOMAIN-SUFFIX,jinkela.red,ğŸ‚ Domestic", // æ¢¯å­
        "DOMAIN-SUFFIX,jinkela.site,ğŸ‚ Domestic", // æ¢¯å­
        "DOMAIN-SUFFIX,epicgames-download1.akamaized.net,ğŸ‚ Domestic", // epic games
        "DOMAIN-SUFFIX,file.myqcloud.com,ğŸ‚ Domestic", // epic games
        "DOMAIN-SUFFIX,epicgames.com,ğŸ‚ Domestic", // epic games
        "DOMAIN-SUFFIX,steamcontent.com,ğŸ‚ Domestic", // steam download
      ]
    );
    return content;
  };
showNewVersionIcon: true
editor: 0
hideAfterStartup: true
randomControllerPort: true
mixinText: |
  mixin: # object
runTimeFormat: "hh : mm : ss"
systemTheme: true
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
trayColorTransparent: false
trayScriptManualRunTime: 1645191482532
useSystemEmoji: true
trayText: ""
connShowProcess: true
showTrayProxyDelayIndicator: true
randomMixedPort: false
