theme: 2
showNotifications: true
fontFamily: TsangerJinKai01-27533
mixinType: 1
mixinCode: |-
  module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
    const rules = [
      ...content.rules,
      'DOMAIN-SUFFIX,qima-inc.com,ğŸš€ç›´æ¥è¿æ¥', // å…¬å¸å†…ç½‘
      'DOMAIN-SUFFIX,delivery.mp.microsoft.com,ğŸš€ç›´æ¥è¿æ¥', // åº”ç”¨å•†åº—æ™ºèƒ½åˆ†å‘
      'DOMAIN-SUFFIX,xvcf1.xboxlive.com,ğŸš€ç›´æ¥è¿æ¥', // xboxä¸‹è½½
      'DOMAIN-SUFFIX,jinkela.red,ğŸš€ç›´æ¥è¿æ¥', // æ¢¯å­
      // 'DOMAIN-SUFFIX,reddit.com,ğŸŒ å›½å¤–åª’ä½“',
      // 'DOMAIN-SUFFIX,redditstatic.com,ğŸŒ å›½å¤–åª’ä½“',
      // 'DOMAIN-SUFFIX,redditmedia.com,ğŸŒ å›½å¤–åª’ä½“',
    ];
    return { ...content, rules };
  }
showNewVersionIcon: true
editor: 1
hideAfterStartup: true
randomControllerPort: true
mixinText: |
  mixin: # object
